apiVersion: v1
kind: Service
metadata:
  name: amuhub-service
spec:
  type: NodePort
  selector:
    app: amuhub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 31000
